###############################################################################
# main code for Qing, Lassiter, & Degen (2018) 
# What do eye movements in the visual world reflect? A case study from adjectives.
# CogSci 2018
# 
# - Ciyang Qing (qciyang@gmail.com) 
# 
# (part of the code was adapted from leffel et al.'s original code 
#  which is in tim-salt2016-plotting-summary-nov17.r
#  their code was written pre-tidyverse, so there were some modifications here
#  but Figure 3 in our paper was still generated by their original code)
#
#
# Input files:
# - vwp_impr_data.csv (eyetracking data from leffel et al 2016)
# - stimuli_all.csv   (information about the stimuli)
# - clickdata.csv     (click data from our own MTurk experiment)
# - production.csv    
#   (output of processFreeProduction.R containing
#    production probabilities of the target adjective derived in various ways, 
#    for this paper we used exact match of the first word because arguably
#    this is closest to the online process in the VWP)
#
#
# below is the description from leffel et al.'s original analysis code  
# this script takes preprocessed eye-tracking from 2x2 grid VWP data
# and generates summary statistics and spaghetti plots
# 
# see leffel, xiang, + kennedy 2016 SALT paper for details
# 
#   -tim (tjleffel@gmail.com)
#
###############################################################################

# load required packages
library(tidyverse)
library(forcats)
library(scales)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))


clickdat <- read.csv("../data/clickdata.csv")
proddat <- read.csv("../data/production.csv")

# read in wide format eyetracking data 
dat <- read.csv("../data/vwp_impr_data.csv")

# cut to TlessC and TmoreC (the SALT 2016 data)
#dat <- droplevels(dat[dat$group %in% c("TmoreC","TlessC"), ])

# cut to TlessC only for CAMP 2017
dat <- droplevels(dat[dat$group == "TlessC", ])

# code subj id as a factor
dat$subject <- as.factor(dat$subject)

# check nouns
#table(dat$group,dat$target.noun)

# correct misspelled factor level (noun "cirlce")
dat$target.noun <- as.character(dat$target.noun)
dat$target.noun <- ifelse(
  dat$target.noun=="cirlce","circle",dat$target.noun
)
dat$target.noun <- as.factor(dat$target.noun)

# check adjectives
# note 'empty' items had wrong pics in TmoreC and TequalC, were thrown out
#table(dat$group,dat$target.adjective)

# check number of subj (track loss subj's already removed)
#length(levels(droplevels(dat[dat$group=="TmoreC", ]$subject))) # 26 subj TmoreC
#length(levels(droplevels(dat[dat$group=="TlessC", ]$subject))) # 21 subj TlessC

# get frame w only relative and maximum (analyzed in SALT paper)
dat <- droplevels(dat[dat$adjectivetype %in% c("max","rel"), ])

# check that there are 72 rows per item per subj (except 15/20, 'empty') 
# also 68@id 39 subj 6866 and 69@id 15 subj 6460
#xtabs(~itemid+subject, data=dat)

# want to reshape to long format w.r.t. display objects 
# (target, competitor, distractor.contrast, distractor)
# datLong = dat %>%
#   gather(variable, value, -trialPosition, -subject, -trialid, -condition, -trialtype, -adjectivetype, -adjectiveonset, -nounonset, -itemid, -target.noun, -target.adjective, -target.color, -timestampsec, -timestampmicrosec, -validityrighteye, -preview.window, -adjective.window, -noun.window, -group, - timeline, - timeslice)

# reshape to long format:
datLong <- dat %>% 
  gather(variable, value, target, competitor, distractor.contrast, distractor)

# eliminate lost data
datLong <- datLong[datLong$value != -1, ]

# get time in ms, post adj-onset (timeslice 0 is time-locked to adj onset)
datLong$time <- datLong$timeslice * 16.66

# prior window: adjective onset to adjective onset+200ms
datLong$window_prior = ifelse(datLong$time < 200, T, F)
# adjective window: noun onset to noun onset + 200
datLong$window_adjective = ifelse(datLong$time >= (datLong$nounonset - datLong$adjectiveonset) & datLong$time < (datLong$nounonset - datLong$adjectiveonset + 200), T, F)
# noun window: noun onset + 500ms to 700ms later
datLong$window_noun = ifelse(datLong$time >= (datLong$nounonset - datLong$adjectiveonset + 200 +300) & datLong$time < (datLong$nounonset - datLong$adjectiveonset + 200 + 500), T, F)




# exclude those cases that fall into no window
datLong = droplevels(datLong[datLong$window_noun | datLong$window_prior | datLong$window_adjective,])
datLong$Region = as.factor(datLong$variable)
datLong$Window = "prior"
datLong[datLong$window_adjective,]$Window = "adjective"
datLong[datLong$window_noun,]$Window = "noun"
summary(datLong)

# get only eye data for TlessC condition
props_diff = datLong %>%
  filter(group == "TlessC" & value == 1) %>%
  group_by(condition,target.adjective,target.noun,target.color,itemid,adjectivetype,Window,Region) %>%
  summarise (totalLooks = n()) %>%
  mutate(Proportion = totalLooks / sum(totalLooks))

# write.csv(props_diff, file="eyedata.csv",row.names=F,quote=F)


eyedat <- ungroup(props_diff) %>% arrange(itemid, condition)


ed <- eyedat %>%
  select(condition, itemid, Window, Region, totalLooks, Proportion) %>%
  rename(prop.eye = Proportion, freq.eye = totalLooks) %>%
  mutate(Region = recode(Region, distractor.contrast = "contrast")) %>%
  arrange(itemid, condition) %>%
  complete(condition, itemid, Window, Region, fill = list(prop.eye = 0, freq.eye = 0))


cd <- clickdat %>%
  filter(Condition %in% c("Contrast","NoContrast")) %>%
  select(SceneID, Condition, Answer.choicePrior, Answer.choiceAdj, Answer.choiceWhole) %>%
  gather(Window, Region, -SceneID, -Condition) %>%
  mutate(Region = tolower(Region), Condition = tolower(Condition)) %>%
  mutate(Window = recode(Window, Answer.choicePrior = "prior",  Answer.choiceAdj = "adjective", Answer.choiceWhole = "noun")) %>%
  group_by(SceneID, Condition, Window, Region) %>%
  summarise (n = n()) %>%
  ungroup() %>%
  complete(SceneID, Condition, Window, Region, fill = list(n=0)) %>%
  group_by(SceneID, Condition, Window) %>%
  mutate(freq = n / sum(n)) %>%
  rename(condition = Condition, itemid = SceneID, prop.click=freq, freq.click=n)



ecd = full_join(ed,cd,by=c("condition","itemid","Window","Region")) %>%
  filter(!is.na(prop.eye)) %>%
  replace_na(list(prop.click = 0, freq.click = 0))

#write.csv(ecd, file="eyeclickdata.csv",row.names=F,quote=F)



cdPlotDat <- ecd %>%
  mutate(AdjectiveType = ifelse(itemid <=20, "max", "rel")) %>%
  group_by(condition, AdjectiveType, Window, Region) %>%
  summarise(prop.click = mean(prop.click)) %>%
  filter(Region == "target" | Region == "competitor") %>%
  ungroup()  %>%
  mutate(Window = fct_relevel(Window, "prior", "adjective", "noun"))

cdPlot <- ggplot(cdPlotDat%>%mutate(Region=fct_relevel(Region,"target", "competitor")) %>% 
                   mutate(AdjectiveType = sub("max", "Maximum", AdjectiveType)) %>%
                   mutate(AdjectiveType = sub("rel", "Relative", AdjectiveType)) %>% 
                   mutate(condition = sub("^contrast", "Contrast", condition)) %>%
                   mutate(condition = sub("^nocontrast", "No contrast", condition)), 
                 aes(x=Window,y=prop.click,color=Region, group=Region)) +
  scale_color_manual(values=c("olivedrab4", "orange")) + 
  geom_point(position=position_dodge(width=0.1))+
  geom_line(position=position_dodge(width=0.1)) +
  ylim(0, 1) +
  ylab("Proportion of clicks") +
  geom_errorbar(aes(ymin=prop.click - 1.96 / sqrt(ifelse(AdjectiveType == "Maximum", 500, 1000)) * sqrt(prop.click*(1-prop.click)),
                    ymax=prop.click + 1.96 / sqrt(ifelse(AdjectiveType == "Maximum", 500, 1000)) * sqrt(prop.click*(1-prop.click))),
                width=.25, position=position_dodge(width=0.1))+
  facet_grid(condition~AdjectiveType)
ggsave("../graphs/clickdat.png", cdPlot, width = 5, height = 2.5)

prodPlotDat <-proddat %>% 
  filter(AdjectiveType != "Min") %>%
  group_by(Condition, AdjectiveType) %>% 
  summarise(prod = mean(ExactFirstWordUniPrior)) %>%
  ungroup() %>%
  mutate(Condition = fct_relevel(Condition, "NoContrast", "Contrast"))

prodPlot <- ggplot(prodPlotDat %>% 
                     mutate(AdjectiveType = sub("max", "Maximum", AdjectiveType)) %>%
                     mutate(AdjectiveType = sub("rel", "Relative", AdjectiveType)) %>% 
                     mutate(Condition = sub("NoContrast", "No contrast", Condition)), 
                   aes(x=Condition,y=prod,color=AdjectiveType)) +
  geom_point(position=position_dodge(width=0.1))+
  ylim(0, .1) +
  ylab("Probability of first word being target adjective") +
  geom_errorbar(aes(ymin=prod - 1.96 / sqrt(ifelse(AdjectiveType == "Maximum", 300, 1000)) * sqrt(prod*(1-prod)),
                    ymax=prod + 1.96 / sqrt(ifelse(AdjectiveType == "Maximum", 300, 600)) * sqrt(prod*(1-prod))),
                width=.25, position=position_dodge(width=0.1))
ggsave("../graphs/freeprodPlot.png", prodPlot, width = 6, height = 3.8)

# generate correlation plots
theme_set(theme_bw())
df <- ecd

df <- df %>%
  mutate(Window = fct_relevel(Window, "prior", "adjective", "noun"))



stimuli_all <- 
  read.csv("../data/stimuli_all.csv") %>% 
  select(Input.List, SceneID, Condition, 
         TargetNoun, TargetAdjective, TargetColor, AdjectiveType) %>%
  rename(itemid = SceneID, condition = Condition) %>%
  mutate(condition = tolower(condition))

df <- df %>% 
  left_join(stimuli_all) %>%
  filter(Input.List == "TlessC1" | Input.List == "TlessC2")

# prior window
priorPlot <- ggplot(df %>% filter(Window == "prior") %>%
                      mutate(AdjectiveType = ifelse(itemid <=20, "Maximum", "Relative")), 
                    aes(x=prop.click,y=prop.eye,color=Region)) +
  geom_abline(intercept=0,slope=1,linetype="dashed",color="gray40") +
  geom_point() +
  xlim(0, 1) + ylim(0, 1) +
  geom_smooth(method="lm",aes(group=1)) +
  geom_text(aes(x, y, label=lab, color=NULL),
            data=data.frame(x=0.2, y=0.9, color="black",
                            AdjectiveType=c("Maximum", "Relative"),
                            lab=c("r = 0.029\n n.s.", "r = 0.003\n n.s."))) +
  xlab("Proportion of clicks") + ylab("Proportion of looks") +
  facet_grid(~AdjectiveType)

ggsave("../graphs/prior.png", priorPlot, width = 6, height = 2.5)


# noun window
nounPlot <- ggplot(df %>% filter(Window == "noun") %>%
                     mutate(AdjectiveType = ifelse(itemid <=20, "Maximum", "Relative")), 
                   aes(x=prop.click,y=prop.eye,color=Region)) +
  geom_abline(intercept=0,slope=1,linetype="dashed",color="gray40") +
  geom_point() +
  xlim(0, 1) + ylim(0, 1) +
  xlab("Proportion of clicks") + ylab("Proportion of looks") +
  geom_smooth(method="lm",aes(group=1)) +
  geom_text(aes(x, y, label=lab, color=NULL),
            data=data.frame(x=0.2, y=0.9, color="black",
                            AdjectiveType=c("Maximum", "Relative"),
                            lab=c("r = 0.817\n ***", "r = 0.802\n ***"))) +
  facet_grid(~AdjectiveType)

ggsave("../graphs/noun.png", nounPlot, width = 6, height = 2.5)


# adjective window
adjPlot <- ggplot(df %>% filter(Window == "adjective") %>%
                    mutate(AdjectiveType = ifelse(itemid <=20, "Maximum", "Relative")) %>%
                    mutate(condition = sub("^contrast",  "Contrast", condition)) %>%
                    mutate(condition = sub("^nocontrast",  "No contrast", condition)), 
                  aes(x=prop.click,y=prop.eye,color=Region)) +
  geom_abline(intercept=0,slope=1,linetype="dashed",color="gray40") +
  geom_point() +
  xlim(0, 1) + ylim(0, 1) +
  xlab("Proportion of clicks") + ylab("Proportion of looks") +
  geom_smooth(method="lm",aes(group=1)) + 
  geom_text(aes(x, y, label=lab, color=NULL),
            data=data.frame(x=0.2, y=0.9, color="black",
                            AdjectiveType=c("Maximum", "Maximum", "Relative", "Relative"),
                            condition = c("Contrast", "No contrast", "Contrast", "No contrast"),
                            lab=c("r = 0.055\n n.s.", "r = 0.281\n **", "r = 0.462\n **", "r = 0.256\n **"))) +
  facet_grid(condition~AdjectiveType)
ggsave("../graphs/adjBrokenDown.png", adjPlot, width = 6, height = 3.5)




